inherit_from: .rubocop_todo.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/*
    - vendor/ruby/**/*
    - config/initializers/simple_form_bootstrap.rb
Rails:
  Enabled: true
