inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - vendor/ruby/**/*
    - config/initializers/simple_form_bootstrap.rb
    - node_moduels/**/*
Rails:
  Enabled: true
