language: ruby
rvm:
  - 2.4.1
bundler_args: --jobs=3 --retry=3 --without production development
cache: bundler
script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec

